# Generated by Django 2.1.7 on 2019-04-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ac_admin', '0001_initial'),
        ('ac_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenRegister',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='citizen/')),
                ('otp', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_login.LoginUser')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='complaints/')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=30)),
                ('close_date', models.DateField(null=True)),
                ('ct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_citizen.CitizenRegister')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_admin.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='feedback/')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_citizen.Complaints')),
                ('ct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_citizen.CitizenRegister')),
            ],
        ),
        migrations.CreateModel(
            name='Reply_feedback',
            fields=[
                ('re_no', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_citizen.Complaints')),
                ('ct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_citizen.CitizenRegister')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_citizen.Feedback')),
            ],
        ),
    ]
